---
# tasks file for php7.4
- name: install packages
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes
  become: yes
  notify:
    - restart apache2
- name: Set PHP settings
  become: yes
  notify:
    - restart apache2
  ini_file:
    dest: /etc/php/7.4/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: Date, option: date.timezone, value: Asia/Kolkata }
    - { section: PHP, option: expose_php, value: Off }
    - { section: PHP, option: display_errors, value: Off }
    - { section: PHP, option: file_uploads, value: On }
    - { section: PHP, option: upload_max_filesize, value: 20M }
    - { section: PHP, option: allow_url_fopen, value: Off }
    - { section: PHP, option: allow_url_include, value: Off }
    - { section: PHP, option: post_max_size, value: 20M }
    - { section: PHP, option: max_execution_time, value: 60 }
    - { section: PHP, option: max_input_time, value: 60 }
    - { section: PHP, option: memory_limit, value: 128M }
    - { section: PHP, option: disable_functions, value: "pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority" }
    - { section: PHP, option: session.save_path, value: "/var/lib/php/sessions" }
    - { section: PHP, option: upload_tmp_dir, value: "/var/lib/php/sessions" }
