mysql_root_password: "{{ mysql_root_password }}"
mysql_root_password_update: yes
mysql_databases:
  - name: example_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: example_user
    host: "localhost"
    password: "{{ mysql_user_password }}"
    priv: "example_db.*:ALL"